using NemesisEuchre.Foundation.Constants;
using NemesisEuchre.GameEngine.PlayerDecisionEngine;
using NemesisEuchre.MachineLearning.Models;

namespace NemesisEuchre.MachineLearning.FeatureEngineering;

public interface IPlayCardInferenceFeatureBuilder
{
    PlayCardTrainingData BuildFeatures(
        RelativeCard[] cardsInHand,
        RelativePlayerPosition leadPlayer,
        RelativeSuit? leadSuit,
        Dictionary<RelativePlayerPosition, RelativeCard> playedCards,
        short teamScore,
        short opponentScore,
        RelativePlayerPosition callingPlayer,
        bool callingPlayerGoingAlone,
        RelativePlayerPosition dealer,
        RelativeCard? dealerPickedUpCard,
        RelativePlayerSuitVoid[] knownPlayerSuitVoids,
        RelativeCard[] cardsAccountedFor,
        RelativePlayerPosition? winningTrickPlayer,
        short trickNumber,
        short wonTricks,
        short opponentsWonTricks,
        RelativeCard chosenCard);
}

public class PlayCardInferenceFeatureBuilder : IPlayCardInferenceFeatureBuilder
{
    public PlayCardTrainingData BuildFeatures(
        RelativeCard[] cardsInHand,
        RelativePlayerPosition leadPlayer,
        RelativeSuit? leadSuit,
        Dictionary<RelativePlayerPosition, RelativeCard> playedCards,
        short teamScore,
        short opponentScore,
        RelativePlayerPosition callingPlayer,
        bool callingPlayerGoingAlone,
        RelativePlayerPosition dealer,
        RelativeCard? dealerPickedUpCard,
        RelativePlayerSuitVoid[] knownPlayerSuitVoids,
        RelativeCard[] cardsAccountedFor,
        RelativePlayerPosition? winningTrickPlayer,
        short trickNumber,
        short wonTricks,
        short opponentsWonTricks,
        RelativeCard chosenCard)
    {
        var context = new PlayCardFeatureBuilderContext(
            cardsInHand,
            playedCards,
            teamScore,
            opponentScore,
            leadPlayer,
            leadSuit,
            callingPlayer,
            callingPlayerGoingAlone,
            dealer,
            dealerPickedUpCard,
            knownPlayerSuitVoids,
            cardsAccountedFor,
            winningTrickPlayer,
            trickNumber,
            wonTricks,
            opponentsWonTricks,
            chosenCard);

        var full = PlayCardFeatureBuilder.BuildFeatures(context);

        return new PlayCardTrainingData
        {
            Card1Rank = full.Card1Rank,
            Card1Suit = full.Card1Suit,
            Card2Rank = full.Card2Rank,
            Card2Suit = full.Card2Suit,
            Card3Rank = full.Card3Rank,
            Card3Suit = full.Card3Suit,
            Card4Rank = full.Card4Rank,
            Card4Suit = full.Card4Suit,
            Card5Rank = full.Card5Rank,
            Card5Suit = full.Card5Suit,
            LeadPlayer = full.LeadPlayer,
            LeadSuit = full.LeadSuit,
            LeftHandOpponentPlayedCardRank = full.LeftHandOpponentPlayedCardRank,
            LeftHandOpponentPlayedCardSuit = full.LeftHandOpponentPlayedCardSuit,
            PartnerPlayedCardRank = full.PartnerPlayedCardRank,
            PartnerPlayedCardSuit = full.PartnerPlayedCardSuit,
            RightHandOpponentPlayedCardRank = full.RightHandOpponentPlayedCardRank,
            RightHandOpponentPlayedCardSuit = full.RightHandOpponentPlayedCardSuit,
            TeamScore = full.TeamScore,
            OpponentScore = full.OpponentScore,
            TrickNumber = full.TrickNumber,
            CardsPlayedInTrick = full.CardsPlayedInTrick,
            WinningTrickPlayer = full.WinningTrickPlayer,
            ChosenCardRank = full.ChosenCardRank,
            ChosenCardRelativeSuit = full.ChosenCardRelativeSuit,
            CallingPlayerPosition = full.CallingPlayerPosition,
            CallingPlayerGoingAlone = full.CallingPlayerGoingAlone,
            DealerPlayerPosition = full.DealerPlayerPosition,
            DealerPickedUpCardRank = full.DealerPickedUpCardRank,
            DealerPickedUpCardSuit = full.DealerPickedUpCardSuit,
            LeftHandOpponentMayHaveTrump = full.LeftHandOpponentMayHaveTrump,
            LeftHandOpponentMayHaveNonTrumpSameColor = full.LeftHandOpponentMayHaveNonTrumpSameColor,
            LeftHandOpponentMayHaveNonTrumpOppositeColor1 = full.LeftHandOpponentMayHaveNonTrumpOppositeColor1,
            LeftHandOpponentMayHaveNonTrumpOppositeColor2 = full.LeftHandOpponentMayHaveNonTrumpOppositeColor2,
            PartnerMayHaveTrump = full.PartnerMayHaveTrump,
            PartnerMayHaveNonTrumpSameColor = full.PartnerMayHaveNonTrumpSameColor,
            PartnerMayHaveNonTrumpOppositeColor1 = full.PartnerMayHaveNonTrumpOppositeColor1,
            PartnerMayHaveNonTrumpOppositeColor2 = full.PartnerMayHaveNonTrumpOppositeColor2,
            RightHandOpponentMayHaveTrump = full.RightHandOpponentMayHaveTrump,
            RightHandOpponentMayHaveNonTrumpSameColor = full.RightHandOpponentMayHaveNonTrumpSameColor,
            RightHandOpponentMayHaveNonTrumpOppositeColor1 = full.RightHandOpponentMayHaveNonTrumpOppositeColor1,
            RightHandOpponentMayHaveNonTrumpOppositeColor2 = full.RightHandOpponentMayHaveNonTrumpOppositeColor2,
            RightBowerOfTrumpHasBeenAccountedFor = full.RightBowerOfTrumpHasBeenAccountedFor,
            LeftBowerOfTrumpHasBeenAccountedFor = full.LeftBowerOfTrumpHasBeenAccountedFor,
            AceOfTrumpHasBeenAccountedFor = full.AceOfTrumpHasBeenAccountedFor,
            KingOfTrumpHasBeenAccountedFor = full.KingOfTrumpHasBeenAccountedFor,
            QueenOfTrumpHasBeenAccountedFor = full.QueenOfTrumpHasBeenAccountedFor,
            TenOfTrumpHasBeenAccountedFor = full.TenOfTrumpHasBeenAccountedFor,
            NineOfTrumpHasBeenAccountedFor = full.NineOfTrumpHasBeenAccountedFor,
            AceOfNonTrumpSameColorHasBeenAccountedFor = full.AceOfNonTrumpSameColorHasBeenAccountedFor,
            KingOfNonTrumpSameColorHasBeenAccountedFor = full.KingOfNonTrumpSameColorHasBeenAccountedFor,
            QueenOfNonTrumpSameColorHasBeenAccountedFor = full.QueenOfNonTrumpSameColorHasBeenAccountedFor,
            TenOfNonTrumpSameColorHasBeenAccountedFor = full.TenOfNonTrumpSameColorHasBeenAccountedFor,
            NineOfNonTrumpSameColorHasBeenAccountedFor = full.NineOfNonTrumpSameColorHasBeenAccountedFor,
            AceOfNonTrumpOppositeColor1HasBeenAccountedFor = full.AceOfNonTrumpOppositeColor1HasBeenAccountedFor,
            KingOfNonTrumpOppositeColor1HasBeenAccountedFor = full.KingOfNonTrumpOppositeColor1HasBeenAccountedFor,
            QueenOfNonTrumpOppositeColor1HasBeenAccountedFor = full.QueenOfNonTrumpOppositeColor1HasBeenAccountedFor,
            JackOfNonTrumpOppositeColor1HasBeenAccountedFor = full.JackOfNonTrumpOppositeColor1HasBeenAccountedFor,
            TenOfNonTrumpOppositeColor1HasBeenAccountedFor = full.TenOfNonTrumpOppositeColor1HasBeenAccountedFor,
            NineOfNonTrumpOppositeColor1HasBeenAccountedFor = full.NineOfNonTrumpOppositeColor1HasBeenAccountedFor,
            AceOfNonTrumpOppositeColor2HasBeenAccountedFor = full.AceOfNonTrumpOppositeColor2HasBeenAccountedFor,
            KingOfNonTrumpOppositeColor2HasBeenAccountedFor = full.KingOfNonTrumpOppositeColor2HasBeenAccountedFor,
            QueenOfNonTrumpOppositeColor2HasBeenAccountedFor = full.QueenOfNonTrumpOppositeColor2HasBeenAccountedFor,
            JackOfNonTrumpOppositeColor2HasBeenAccountedFor = full.JackOfNonTrumpOppositeColor2HasBeenAccountedFor,
            TenOfNonTrumpOppositeColor2HasBeenAccountedFor = full.TenOfNonTrumpOppositeColor2HasBeenAccountedFor,
            NineOfNonTrumpOppositeColor2HasBeenAccountedFor = full.NineOfNonTrumpOppositeColor2HasBeenAccountedFor,
            WonTricks = full.WonTricks,
            OpponentsWonTricks = full.OpponentsWonTricks,
        };
    }
}
