// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NemesisEuchre.DataAccess;

#nullable disable

namespace NemesisEuchre.DataAccess.Migrations
{
    [DbContext(typeof(NemesisEuchreDbContext))]
    [Migration("20260130150822_AddCallingPlayerToPlayCardDecisions")]
    partial class AddCallingPlayerToPlayCardDecisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.CallTrumpDecisionEntity", b =>
                {
                    b.Property<int>("CallTrumpDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallTrumpDecisionId"));

                    b.Property<string>("ActorType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CardsInHandJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChosenDecisionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("DealerPosition")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte>("DecisionOrder")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("DidTeamWinDeal")
                        .HasColumnType("bit");

                    b.Property<bool?>("DidTeamWinGame")
                        .HasColumnType("bit");

                    b.Property<short>("OpponentScore")
                        .HasColumnType("smallint");

                    b.Property<short?>("RelativeDealPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("TeamScore")
                        .HasColumnType("smallint");

                    b.Property<string>("UpCardJson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValidDecisionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CallTrumpDecisionId");

                    b.HasIndex("ActorType")
                        .HasDatabaseName("IX_CallTrumpDecisions_ActorType");

                    b.HasIndex("DealId")
                        .HasDatabaseName("IX_CallTrumpDecisions_DealId");

                    b.ToTable("CallTrumpDecisions", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DealEntity", b =>
                {
                    b.Property<int>("DealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DealId"));

                    b.Property<string>("CallingPlayer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("CallingPlayerIsGoingAlone")
                        .HasColumnType("bit");

                    b.Property<int>("DealNumber")
                        .HasColumnType("int");

                    b.Property<string>("DealResult")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DealStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DealerPosition")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DeckJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("PlayersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Team1Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Team2Score")
                        .HasColumnType("smallint");

                    b.Property<string>("Trump")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpCardJson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WinningTeam")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DealId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("IX_Deals_GameId");

                    b.ToTable("Deals", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DiscardCardDecisionEntity", b =>
                {
                    b.Property<int>("DiscardCardDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscardCardDecisionId"));

                    b.Property<string>("ActorType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CallingPlayer")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("CallingPlayerGoingAlone")
                        .HasColumnType("bit");

                    b.Property<string>("CardsInHandJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChosenCardJson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<bool?>("DidTeamWinDeal")
                        .HasColumnType("bit");

                    b.Property<bool?>("DidTeamWinGame")
                        .HasColumnType("bit");

                    b.Property<short>("OpponentScore")
                        .HasColumnType("smallint");

                    b.Property<short?>("RelativeDealPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("TeamScore")
                        .HasColumnType("smallint");

                    b.HasKey("DiscardCardDecisionId");

                    b.HasIndex("ActorType")
                        .HasDatabaseName("IX_DiscardCardDecisions_ActorType");

                    b.HasIndex("DealId")
                        .HasDatabaseName("IX_DiscardCardDecisions_DealId");

                    b.ToTable("DiscardCardDecisions", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.GameEntity", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GameStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlayersJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<short>("Team1Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Team2Score")
                        .HasColumnType("smallint");

                    b.Property<string>("WinningTeam")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("GameId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Games_CreatedAt");

                    b.HasIndex("WinningTeam")
                        .HasDatabaseName("IX_Games_WinningTeam");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.PlayCardDecisionEntity", b =>
                {
                    b.Property<int>("PlayCardDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayCardDecisionId"));

                    b.Property<string>("ActorType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CallingPlayer")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("CallingPlayerGoingAlone")
                        .HasColumnType("bit");

                    b.Property<string>("CardsInHandJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChosenCardJson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<bool?>("DidTeamWinDeal")
                        .HasColumnType("bit");

                    b.Property<bool?>("DidTeamWinGame")
                        .HasColumnType("bit");

                    b.Property<bool?>("DidTeamWinTrick")
                        .HasColumnType("bit");

                    b.Property<string>("LeadPlayer")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LeadSuit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<short>("OpponentScore")
                        .HasColumnType("smallint");

                    b.Property<string>("PlayedCardsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("RelativeDealPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("TeamScore")
                        .HasColumnType("smallint");

                    b.Property<int>("TrickId")
                        .HasColumnType("int");

                    b.Property<string>("ValidCardsToPlayJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinningTrickPlayer")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("PlayCardDecisionId");

                    b.HasIndex("ActorType")
                        .HasDatabaseName("IX_PlayCardDecisions_ActorType");

                    b.HasIndex("DealId")
                        .HasDatabaseName("IX_PlayCardDecisions_DealId");

                    b.HasIndex("TrickId")
                        .HasDatabaseName("IX_PlayCardDecisions_TrickId");

                    b.ToTable("PlayCardDecisions", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.TrickEntity", b =>
                {
                    b.Property<int>("TrickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrickId"));

                    b.Property<string>("CardsPlayedJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("LeadPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LeadSuit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TrickNumber")
                        .HasColumnType("int");

                    b.Property<string>("WinningPosition")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("WinningTeam")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TrickId");

                    b.HasIndex("DealId")
                        .HasDatabaseName("IX_Tricks_DealId");

                    b.ToTable("Tricks", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.CallTrumpDecisionEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.DealEntity", "Deal")
                        .WithMany("CallTrumpDecisions")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DealEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.GameEntity", "Game")
                        .WithMany("Deals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DiscardCardDecisionEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.DealEntity", "Deal")
                        .WithMany("DiscardCardDecisions")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.PlayCardDecisionEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.DealEntity", "Deal")
                        .WithMany("PlayCardDecisions")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NemesisEuchre.DataAccess.Entities.TrickEntity", "Trick")
                        .WithMany("PlayCardDecisions")
                        .HasForeignKey("TrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");

                    b.Navigation("Trick");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.TrickEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.DealEntity", "Deal")
                        .WithMany("Tricks")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DealEntity", b =>
                {
                    b.Navigation("CallTrumpDecisions");

                    b.Navigation("DiscardCardDecisions");

                    b.Navigation("PlayCardDecisions");

                    b.Navigation("Tricks");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.GameEntity", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.TrickEntity", b =>
                {
                    b.Navigation("PlayCardDecisions");
                });
#pragma warning restore 612, 618
        }
    }
}
