// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NemesisEuchre.DataAccess;

#nullable disable

namespace NemesisEuchre.DataAccess.Migrations
{
    [DbContext(typeof(NemesisEuchreDbContext))]
    [Migration("20260127015659_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.CallTrumpDecisionEntity", b =>
                {
                    b.Property<int>("CallTrumpDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallTrumpDecisionId"));

                    b.Property<int?>("ActorType")
                        .HasColumnType("int");

                    b.Property<string>("ChosenDecisionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<int>("DealerPosition")
                        .HasColumnType("int");

                    b.Property<int>("DecidingPlayerPosition")
                        .HasColumnType("int");

                    b.Property<byte>("DecisionOrder")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("DidTeamWinDeal")
                        .HasColumnType("bit");

                    b.Property<bool?>("DidTeamWinGame")
                        .HasColumnType("bit");

                    b.Property<string>("HandJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("OpponentScore")
                        .HasColumnType("smallint");

                    b.Property<short>("TeamScore")
                        .HasColumnType("smallint");

                    b.Property<string>("UpCardJson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValidDecisionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CallTrumpDecisionId");

                    b.HasIndex("ActorType")
                        .HasDatabaseName("IX_CallTrumpDecisions_ActorType");

                    b.HasIndex("DealId")
                        .HasDatabaseName("IX_CallTrumpDecisions_DealId");

                    b.ToTable("CallTrumpDecisions", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DealEntity", b =>
                {
                    b.Property<int>("DealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DealId"));

                    b.Property<int?>("CallingPlayer")
                        .HasColumnType("int");

                    b.Property<bool>("CallingPlayerIsGoingAlone")
                        .HasColumnType("bit");

                    b.Property<int>("DealNumber")
                        .HasColumnType("int");

                    b.Property<int?>("DealResult")
                        .HasColumnType("int");

                    b.Property<int>("DealStatus")
                        .HasColumnType("int");

                    b.Property<int?>("DealerPosition")
                        .HasColumnType("int");

                    b.Property<string>("DeckJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("PlayersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Team1Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Team2Score")
                        .HasColumnType("smallint");

                    b.Property<int?>("Trump")
                        .HasColumnType("int");

                    b.Property<string>("UpCardJson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("WinningTeam")
                        .HasColumnType("int");

                    b.HasKey("DealId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("IX_Deals_GameId");

                    b.ToTable("Deals", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DiscardCardDecisionEntity", b =>
                {
                    b.Property<int>("DiscardCardDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscardCardDecisionId"));

                    b.Property<int?>("ActorType")
                        .HasColumnType("int");

                    b.Property<string>("ChosenCardJson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<int>("DealerPosition")
                        .HasColumnType("int");

                    b.Property<bool?>("DidTeamWinDeal")
                        .HasColumnType("bit");

                    b.Property<bool?>("DidTeamWinGame")
                        .HasColumnType("bit");

                    b.Property<string>("HandJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("OpponentScore")
                        .HasColumnType("smallint");

                    b.Property<short>("TeamScore")
                        .HasColumnType("smallint");

                    b.Property<string>("ValidCardsToDiscardJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiscardCardDecisionId");

                    b.HasIndex("ActorType")
                        .HasDatabaseName("IX_DiscardCardDecisions_ActorType");

                    b.HasIndex("DealId")
                        .HasDatabaseName("IX_DiscardCardDecisions_DealId");

                    b.ToTable("DiscardCardDecisions", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.GameEntity", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GameStatus")
                        .HasColumnType("int");

                    b.Property<string>("PlayersJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<short>("Team1Score")
                        .HasColumnType("smallint");

                    b.Property<short>("Team2Score")
                        .HasColumnType("smallint");

                    b.Property<int?>("WinningTeam")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Games_CreatedAt");

                    b.HasIndex("WinningTeam")
                        .HasDatabaseName("IX_Games_WinningTeam");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.PlayCardDecisionEntity", b =>
                {
                    b.Property<int>("PlayCardDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayCardDecisionId"));

                    b.Property<int?>("ActorType")
                        .HasColumnType("int");

                    b.Property<string>("ChosenCardJson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CurrentTrickJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<int>("DecidingPlayerPosition")
                        .HasColumnType("int");

                    b.Property<bool?>("DidTeamWinDeal")
                        .HasColumnType("bit");

                    b.Property<bool?>("DidTeamWinGame")
                        .HasColumnType("bit");

                    b.Property<bool?>("DidTeamWinTrick")
                        .HasColumnType("bit");

                    b.Property<string>("HandJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadPosition")
                        .HasColumnType("int");

                    b.Property<short>("OpponentScore")
                        .HasColumnType("smallint");

                    b.Property<short>("TeamScore")
                        .HasColumnType("smallint");

                    b.Property<int>("TrickNumber")
                        .HasColumnType("int");

                    b.Property<string>("ValidCardsToPlayJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayCardDecisionId");

                    b.HasIndex("DealId")
                        .HasDatabaseName("IX_PlayCardDecisions_DealId");

                    b.HasIndex("ActorType", "TrickNumber")
                        .HasDatabaseName("IX_PlayCardDecisions_ActorType_TrickNumber");

                    b.ToTable("PlayCardDecisions", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.TrickEntity", b =>
                {
                    b.Property<int>("TrickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrickId"));

                    b.Property<string>("CardsPlayedJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<int>("LeadPosition")
                        .HasColumnType("int");

                    b.Property<int?>("LeadSuit")
                        .HasColumnType("int");

                    b.Property<int>("TrickNumber")
                        .HasColumnType("int");

                    b.Property<int?>("WinningPosition")
                        .HasColumnType("int");

                    b.Property<int?>("WinningTeam")
                        .HasColumnType("int");

                    b.HasKey("TrickId");

                    b.HasIndex("DealId")
                        .HasDatabaseName("IX_Tricks_DealId");

                    b.ToTable("Tricks", (string)null);
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.CallTrumpDecisionEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.DealEntity", "Deal")
                        .WithMany("CallTrumpDecisions")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DealEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.GameEntity", "Game")
                        .WithMany("Deals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DiscardCardDecisionEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.DealEntity", "Deal")
                        .WithMany("DiscardCardDecisions")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.PlayCardDecisionEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.DealEntity", "Deal")
                        .WithMany("PlayCardDecisions")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.TrickEntity", b =>
                {
                    b.HasOne("NemesisEuchre.DataAccess.Entities.DealEntity", "Deal")
                        .WithMany("Tricks")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.DealEntity", b =>
                {
                    b.Navigation("CallTrumpDecisions");

                    b.Navigation("DiscardCardDecisions");

                    b.Navigation("PlayCardDecisions");

                    b.Navigation("Tricks");
                });

            modelBuilder.Entity("NemesisEuchre.DataAccess.Entities.GameEntity", b =>
                {
                    b.Navigation("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
